<a href="https://colab.research.google.com/github/jiruneko/calpo_ML/blob/main/calpo_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
data = ['身長', 140, '体重', 40.5]
print(data)

['身長', 140, '体重', 40.5]


In [6]:
class Test:
  def show(self, val):
    print(self, val)

In [8]:
s = str('Python')
print(s)

Python


In [9]:
test = Test()
test.show('こんにちは')

<__main__.Test object at 0x7d0788e2e3e0> こんにちは


In [10]:
test.show('こんにちは')

def show(self, val):
  print(self, val)

<__main__.Test object at 0x7d0788e2e3e0> こんにちは


In [13]:
class Test:
  def __init__(self, val):
    self.val = val

  def show(self):
    print(self.val)

test2 = Test('こんにちは')
test2.show()

こんにちは


In [15]:
import numpy as np

In [16]:
x = np.array(15)
x

array(15)

In [17]:
x.dtype

dtype('int64')

In [18]:
x.ndim

0

In [19]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [20]:
x.ndim

1

In [21]:
x[0]

1

In [22]:
x[2] = 100
x

array([  1,   2, 100])

In [23]:
x = np.array([[10, 15, 20, 25, 30],
             [20, 30, 40, 50, 60],
              [50, 53, 56, 59, 62]])

x

array([[10, 15, 20, 25, 30],
       [20, 30, 40, 50, 60],
       [50, 53, 56, 59, 62]])

In [24]:
x.ndim

2

In [25]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y

array([5, 7, 9])

In [26]:
x - y

array([-3, -3, -3])

In [27]:
x * y

array([ 4, 10, 18])

In [28]:
x / y

array([0.25, 0.4 , 0.5 ])

In [29]:
x = np.array([1, 2, 3, 4, 5], dtype = float)
y = np.array(10)
print(x + y)

[11. 12. 13. 14. 15.]


In [30]:
print(x + 10)

[11. 12. 13. 14. 15.]


In [31]:
print(x - 1)

[0. 1. 2. 3. 4.]


In [32]:
print(x)

[1. 2. 3. 4. 5.]


In [33]:
print(x * 10)

[10. 20. 30. 40. 50.]


In [34]:
print(x / 2)

[0.5 1.  1.5 2.  2.5]


In [35]:
vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

print(vec1 + vec2)

[50 70 90]


In [36]:
print(vec1 - vec2)

[-30 -30 -30]


In [37]:
vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

print(vec1 * vec2)

[ 400 1000 1800]


In [40]:
vec3 = np.array([4, 5, -6])
vec4 = np.array([-2, 3, -1])

np.dot(vec3, vec4)

13

In [41]:
mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               dtype = float)
mtx

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [42]:
print(mtx * 10)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [43]:
print(mtx - 10)

[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]


In [44]:
print(mtx * 2)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [45]:
mtx / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [47]:
A = np.array([[1, 2],
              [3, 4]])
print(3 * A)

[[ 3  6]
 [ 9 12]]


In [48]:
mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               )
mtx.dtype

dtype('int64')

In [52]:
mtx[0]


array([1, 2, 3])

In [54]:
mtx[0,]

array([1, 2, 3])

In [55]:
mtx[0, :]

array([1, 2, 3])

In [56]:
mtx[:, 0]

array([1, 4, 7])

In [57]:
mtx[1,1]

5

In [59]:
mtx[2, 0]

7

In [62]:
mtx[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [64]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])
a + b

array([[5, 5],
       [5, 5]])

In [65]:
a - b

array([[-3, -1],
       [ 1,  3]])

In [66]:
a = np.array([[2, 3],
              [2, 3]])
b = np.array([[3, 4],
              [5, 6]])
a * b

array([[ 6, 12],
       [10, 18]])

In [68]:
c = np.array(([2],
              [3]))
d = np.array(([3, 4],
              [5, 6]))
c * d

array([[ 6,  8],
       [15, 18]])

In [69]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [71]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])